[pytest]
testpaths = tests
python_files = test_*.py
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)-7s | %(message)s
log_cli_date_format = %H:%M:%S
# Drop --headed to run headless (CI).
addopts =
    --html=reports/report.html
    --self-contained-html
    --headed
    --video=on
    --output=videos
